import OrganizationModelType from './OrganizationModel';
import AnnouncementModelType from './AnnouncementModel';
import OfferingModelType from './OfferingModel';
import ExtractModelType from './ExtractModel';
import EdFiRequestModelType from './EdFiRequestModel';
import EdFiODSStatusModelType from './EdFiODSStatusModel';
import EdFiODSClientModelType from './EdFiODSClientModel';
import EdFiODSResourceCountModelType from './EdFiODSResourceCountModel';
import CRMContactModelType from './CRMContactModel';
import SupportModelType from './SupportModel';
import UserModelType from './UserModel';

export type OrganizationModel = OrganizationModelType;
export type AnnouncementModel = AnnouncementModelType;
export type OfferingModel = OfferingModelType;
export type ExtractModel = ExtractModelType;
export type EdFiRequestModel = EdFiRequestModelType;
export type EdFiODSStatusModel = EdFiODSStatusModelType;
export type EdFiODSClientModel = EdFiODSClientModelType;
export type EdFiODSResourceCountModel = EdFiODSResourceCountModelType;
export type CRMContactModel = CRMContactModelType;
export type SupportModel = SupportModelType;
export type UserModel = UserModelType;
