// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class ActivityLog
    {
        public int ActivityLogId { get; set; }
        public int UserId { get; set; }
        public int OrganizationId { get; set; }
        public byte? ChangeType { get; set; }
        public string Description { get; set; }
        public DateTime AsOfDate { get; set; }

        public virtual Organization Organization { get; set; }
        public virtual User User { get; set; }
    }
}