// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class CRMContact
    {
        public int CRMContactId { get; set; }
        public int OrganizationId { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }

        public virtual Organization Organization { get; set; }
    }
}