// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class EdFiRequest
    {
        public int EdFiRequestId { get; set; }
        public int OrganizationId { get; set; }
        public string Description { get; set; }
        public DateTime? RequestDate { get; set; }
        public byte RequestStatus { get; set; }
        public bool IsArchived { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? LastModifiedOn { get; set; }
        public int? LastModifiedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User LastModifiedByNavigation { get; set; }
        public virtual Organization Organization { get; set; }
    }
}