// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class EdFiODS
    {
        public EdFiODS()
        {
            EdFiODSClients = new HashSet<EdFiODSClient>();
            ODSStatuses = new HashSet<ODSStatus>();
        }

        public int EdFiODSId { get; set; }
        public int EdFiODSNo { get; set; }
        public int? OrganizationId { get; set; }
        public string ODSName { get; set; }
        public string ODSPath { get; set; }
        public string ODSURL { get; set; }
        public string ODSVersion { get; set; }
        public string ODSKey { get; set; }
        public string ODSSecret { get; set; }
        public DateTime LastModifiedOn { get; set; }

        public virtual Organization Organization { get; set; }
        public virtual ICollection<EdFiODSClient> EdFiODSClients { get; set; }
        public virtual ICollection<ODSStatus> ODSStatuses { get; set; }
    }
}