// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class EdFiODSClient
    {
        public int EdFiODSClientId { get; set; }
        public int EdFiODSId { get; set; }
        public string VendorName { get; set; }
        public string ApplicationName { get; set; }
        public string ClaimSetName { get; set; }
        public string ClientName { get; set; }
        public string ODSKey { get; set; }
        public string ODSSecret { get; set; }
        public DateTime LastModifiedOn { get; set; }

        public virtual EdFiODS EdFiODS { get; set; }
    }
}