// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class Extract
    {
        public int ExtractId { get; set; }
        public int OrganizationId { get; set; }
        public string ExtractJobName { get; set; }
        public string ExtractFrequency { get; set; }
        public string ExtractLastStatus { get; set; }
        public DateTime? ExtractLastDate { get; set; }

        public virtual Organization Organization { get; set; }
    }
}