// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class ODSStatusJob
    {
        public ODSStatusJob()
        {
            ODSStatuses = new HashSet<ODSStatus>();
        }

        public int ODSStatusJobId { get; set; }
        public int ODSStatusJobNo { get; set; }
        public string StatusJobName { get; set; }
        public string ODSVersion { get; set; }
        public byte ODSCheckType { get; set; }
        public string EntityTableToQuery { get; set; }
        public string FilterConditions { get; set; }

        public virtual ICollection<ODSStatus> ODSStatuses { get; set; }
    }
}