// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class Organization
    {
        public Organization()
        {
            ActivityLogs = new HashSet<ActivityLog>();
            Announcements = new HashSet<Announcement>();
            CRMContacts = new HashSet<CRMContact>();
            EdFiODs = new HashSet<EdFiODS>();
            EdFiRequests = new HashSet<EdFiRequest>();
            Extracts = new HashSet<Extract>();
            Participations = new HashSet<Participation>();
            Supports = new HashSet<Support>();
            Users = new HashSet<User>();
        }

        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationAbbreviation { get; set; }
        public string LocalOrganizationID { get; set; }
        public string FederalOrganizationID { get; set; }
        public int? EducationOrganizationID { get; set; }
        public string SIS { get; set; }
        public string DominantDataSystem { get; set; }
        public string AnalyticsSystem { get; set; }
        public string InterimAssessments { get; set; }

        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<CRMContact> CRMContacts { get; set; }
        public virtual ICollection<EdFiODS> EdFiODs { get; set; }
        public virtual ICollection<EdFiRequest> EdFiRequests { get; set; }
        public virtual ICollection<Extract> Extracts { get; set; }
        public virtual ICollection<Participation> Participations { get; set; }
        public virtual ICollection<Support> Supports { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}