// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class Participation
    {
        public int OrganizationId { get; set; }
        public int OfferingId { get; set; }
        public DateTime AsOfDate { get; set; }

        public virtual Offering Offering { get; set; }
        public virtual Organization Organization { get; set; }
    }
}