// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DataHub.Api.Data.Entities
{
    public partial class Support
    {
        public int SupportId { get; set; }
        public int? OrganizationId { get; set; }
        public string SystemID { get; set; }
        public string TicketID { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }

        public virtual Organization Organization { get; set; }
    }
}