// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using DataHub.Api.Enums;

namespace DataHub.Api.Data.Entities
{
    public partial class User
    {
        public User()
        {
            ActivityLogs = new HashSet<ActivityLog>();
            EdFiRequestCreatedByNavigations = new HashSet<EdFiRequest>();
            EdFiRequestLastModifiedByNavigations = new HashSet<EdFiRequest>();
        }

        public int UserId { get; set; }
        public int OrganizationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public UserRole Role { get; set; }
        public string EmailAddress { get; set; }
        public byte Status { get; set; }

        public virtual Organization Organization { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<EdFiRequest> EdFiRequestCreatedByNavigations { get; set; }
        public virtual ICollection<EdFiRequest> EdFiRequestLastModifiedByNavigations { get; set; }
    }
}